site_url: svd-nuxt.netlify.app

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: "assets/img/uploads"
public_folder: "/img/uploads"
# Used for translation, documentation can be found at https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_files
  locales: [sv, en]
  default_locale: sv
# Specifies what fields should show up on the cms, documentation at https://www.netlifycms.org/docs/collection-types/#header
collections:
  - name: "company"
    label: "company"
    folder: "content/companies" # defines where the files created will be placed
    create: true # allows users to create new files
    slug: "{{title}}" # Defines how the name for a new file created by the cms should look, needs to have {{}} around it
    i18n: true # defines if it uses language translation. Default is false
    fields:
      - {
          label: "Logo", # what the field will be called in the cms part where you enter information, no writing conventions needed
          name: "logo", # Is the name of the field in the file the cms will create, need to be written in snake cases see SVD wiki for info
          widget: "image", # defines the type of data, possible choices found at https://www.netlifycms.org/docs/widgets/#header
          required: false, # defines if the field is mandatory to enter or not
          i18n: duplicate, # will copy the information entered on the default language
        }
      - {
          label: "Title",
          name: "title",
          wiget: "string",
          required: true,
          i18n: duplicate,
        }
      - {
          lable: "Sponsor?",
          name: "sponsor",
          widget: "boolean",
          required: false,
          18n: duplicate,
        }
      - {
          label: "Slogan",
          name: "slogan",
          widget: "string",
          required: false,
          i18n: true, # will require you to enter the information in multiple languages
        }
      - {
          label: "Founded (year)",
          name: "founded",
          widget: "number",
          required: true,
          i18n: duplicate,
        }
      - {
          label: "Location",
          name: "location",
          widget: "string",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Number of employess in Sweden",
          name: "number_of_employees_in_Sweden",
          widget: "number",
          value_type: "int",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Number of employess internationally",
          name: "number_of_employees_in_internationally",
          widget: "number",
          value_type: "int",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Area of business (max 40 words)",
          name: "area_of_business",
          widget: "text",
          required: true,
          i18n: true,
        }
      - {
          label: "About us (max 150 words)",
          name: "about_us",
          widget: "text",
          required: true,
          i18n: true,
        }
      - {
          lable: "Extra text",
          name: "extra_text",
          widget: "markdown",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Qualifications (max 35 words)",
          name: "qualifications",
          widget: "text",
          required: true,
          i18n: true,
        }

      - label: "Contact persons"
        name: "contact_persons"
        widget: "list"
        allow_add: true
        required: false
        i18n: true
        fields:
          - {
              label: "Name",
              name: "name",
              widget: "string",
              required: true,
              i18n: duplicate,
            }
          - {
              label: "Email",
              name: "email",
              widget: "string",
              required: false,
              i18n: duplicate,
            }
          - {
              label: "Phone number",
              name: "phone_number",
              widget: "string",
              required: false,
              i18n: duplicate,
            }

      - {
          label: "Link to postitions",
          name: "link_to_positions",
          widget: "string",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Program",
          name: "program",
          widget: "select",
          multiple: true,
          options:
            [
              "Affärssystem och tjänstedesign",
              "Enterprise Systems and Service Design",
              "Data- och systemvetenskap",
              "Computer and System Sciences",
              "Datorspelsutveckling",
              "Computer Game Development",
              "Datavetenskap",
              Computer Science and Software Engineering,
              "Ekonomi och IT",
              "Administration and Information Technology",
              "Marknadskommunikation och IT",
              "Market Comunication and Information Technology",
              "Digitala medier",
              "Digital media",
              "Interaktionsdesign",
              "Interaction Design",
              "Magister/Master",
              "Master",
            ],
          required: true,
          i18n: true,
        }
      - {
          label: "Positions",
          name: "positions",
          widget: "select",
          multiple: true,
          options:
            [
              "Praktikplatser",
              "Internships",
              "Utlandstjänster",
              "Foreign Services",
              "Traineeprogram",
              "Heltidstjänster",
              "Full time positions",
              "Examensarbete",
              "Thesis project",
              "Deltidstjänster",
              "Part-time positions",
            ],
          required: true,
          i18n: true,
        }
      - {
          label: "Positions other",
          name: "positions_other",
          widget: "string",
          required: false,
          i18n: true,
        }

      - {
          label: "Sponsor banner",
          name: "banner",
          widget: "image",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Youtube video (sponsor)",
          name: "youtube_video",
          widget: "string",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Sponsor images",
          name: "sponsor_images",
          widget: "list",
          allow_add: true,
          required: false,
          i18n: true,
          field:
            {
              label: "Sponsor image",
              name: "sponsor_image",
              widget: image,
              i18n: duplicate,
            },
        }

  - name: "about"
    label: "About"
    folder: "content/about"
    create: true
    slug: "{{name}}"
    i18n: true
    fields:
      - {
          label: "Name",
          name: "name",
          widget: "string",
          required: true,
          i18n: duplicate,
        }
      - {
          label: "Picture",
          name: "picture",
          widget: "image",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Role",
          name: "role",
          widget: "string",
          required: true,
          i18n: duplicate,
        }
      - {
          label: "Group",
          name: "group",
          widget: "select",
          options:
            [
              "General",
              "Business Relations and Sales",
              "Events",
              "Logistics",
              "Marketing",
              "Web Development and Design",
              "Group Leader",
            ],
          required: true,
          i18n: duplicate,
        }
      - {
          label: "Systemvetardagen Year",
          name: "svd_year",
          widget: "datetime",
          date_format: "YYYY",
          time_format: false,
          required: true,
          i18n: duplicate,
        } #returns a time date string of the year
      - {
          label: "About you",
          name: "about_you",
          widget: "text",
          required: false,
          i18n: true,
        }
      - {
          label: "DISK mail",
          name: "disk_mail",
          widget: "string",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Personal mail",
          name: "personal_mail",
          widget: "string",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "LinkedIn link",
          name: "linkedin_link",
          widget: "string",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Portfolio link",
          name: "portfolio_link",
          widget: "text",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Github link",
          name: "github_link",
          widget: "text",
          required: false,
          i18n: duplicate,
        }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{title}}"
    i18n: true
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
          i18n: true,
        }
      - {
          label: "Post image",
          name: "post_image",
          widget: "image",
          required: false,
          i18n: duplicate,
        }
      - {
          label: "Body",
          name: "body_text",
          widget: "markdown",
          required: true,
          i18n: true,
        }
      - {
          label: "Date of creation",
          name: "date_of_creation",
          widget: "date",
          required: true,
          i18n: duplicate,
        }
      - {
          label: "Authors",
          name: "authors",
          widget: "list",
          allow_add: true,
          required: false,
          i18n: true,
          field:
            {
              label: "Author",
              name: "author",
              widget: "string",
              i18n: duplicate,
            },
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          allow_add: true,
          required: false,
          i18n: true,
          field:
            { label: "Image", name: "image", widget: "image", i18n: duplicate },
        }
